// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalrD1Core
{
    public partial class message
    {
        [Key]
        public int id { get; set; }
        [StringLength(150)]
        public string name { get; set; }
        public string txt { get; set; }
    }
}