// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirst.Models
{
    [Table("Course")]
    public partial class Course
    {
        [Key]
        public int Crs_Id { get; set; }
        [StringLength(50)]
        public string Crs_Name { get; set; }
        public int? Crs_Duration { get; set; }
        public int? Top_Id { get; set; }

        [ForeignKey(nameof(Top_Id))]
        [InverseProperty(nameof(Topic.Courses))]
        public virtual Topic Top { get; set; }
    }
}