// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirst.Models
{
    [Table("Topic")]
    public partial class Topic
    {
        public Topic()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        public int Top_Id { get; set; }
        [StringLength(50)]
        public string Top_Name { get; set; }

        [InverseProperty(nameof(Course.Top))]
        public virtual ICollection<Course> Courses { get; set; }
    }
}