// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiCore.Models
{
    [Table("Departments")]
    public partial class Department
    {
        [Key]
        public int Dept_Id { get; set; }
        
        [StringLength(50)]
        public string Dept_Name { get; set; }
        
        [StringLength(100)]
        public string Dept_Desc { get; set; }
        
        [StringLength(50)]
        public string Dept_Location { get; set; }

        //naviagiton to instructors
        public virtual List<Instructor> Instructors { get; set; } = new List<Instructor>();
    }
}