// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiCore.Models
{
    [Table("Instructor")]
    public partial class Instructor
    {
        [Key]
        public int Ins_Id { get; set; }
        
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
        
        [StringLength(50)]
        public string Ins_Name { get; set; }
        
        
        [Column(TypeName = "money")]
        public decimal? Salary { get; set; }

        [ForeignKey("Department")]
        public int? Dept_Id { get; set; }
        
        //navigation ot departemnts
        public Department Department { get; set; }

    }
}