// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day8_Demo_42.Model
{
    [Table("Department")]
    public partial class Department
    {
        public Department()
        {
            customers = new HashSet<customer>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(10)]
        public string Name { get; set; }

        [InverseProperty(nameof(customer.Dept))]
        public virtual ICollection<customer> customers { get; set; }
    }
}