// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFGridView.Entites
{
    public partial class Employee
    {
        [Required]
        public string Name { get; set; }
        public int Age { get; set; }
        [Required]
        [StringLength(1)]
        public string Gender { get; set; }
        public float Salary { get; set; }
        [Key]
        public int Id { get; set; }
    }
}