// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWindConsole.Context
{
    public partial class TestPrdResult
    {
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
    }
}
